name: cryptkeep
description: "CryptKeep — zero-knowledge password manager by EERIE"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  uuid: ^4.5.1
  provider: ^6.1.2
  kdbx: ^2.4.2
  file_picker: ^8.0.0
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.7

msix_config:
  display_name: CryptKeep
  publisher_display_name: EERIE
  identity_name: 20715EerieGoesD.CryptKeep
  publisher: CN=A2A89A47-0B2B-4C32-B85C-9753888A9FFC
  msix_version: 1.0.1.0
  logo_path: windows/runner/resources/app_icon.ico
  capabilities: internetClient
  store: true

flutter:
  uses-material-design: true
