# Release builds shrink code with R8, which warns about classes that are
# referenced but not present. These come from the logging libraries pulled in
# for flutter_autofill_service (tinylog + kotlin-logging): they can talk to
# several logging backends and to desktop-only JVM APIs, none of which ship in
# an Android app. Nothing here is called at runtime, so the warnings are safe
# to silence. Generated by the build itself at
# build/app/outputs/mapping/release/missing_rules.txt.

# Optional logback backend (we use tinylog's logcat writer instead).
-dontwarn ch.qos.logback.classic.Level
-dontwarn ch.qos.logback.classic.Logger
-dontwarn ch.qos.logback.classic.LoggerContext
-dontwarn ch.qos.logback.classic.spi.ILoggingEvent
-dontwarn ch.qos.logback.classic.spi.LoggingEvent

# Desktop JVM APIs that do not exist on Android.
-dontwarn java.lang.ProcessHandle
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.RuntimeMXBean
-dontwarn javax.naming.InitialContext
-dontwarn javax.naming.NameNotFoundException
-dontwarn javax.naming.NamingException
-dontwarn sun.reflect.Reflection

# The autofill plugin looks this provider up by name from
# resources/META-INF/services, so R8 cannot see the reference and would
# otherwise strip or rename it - which crashes the autofill service on start.
-keep class com.keevault.flutter_autofill_service.DynamicLevelLoggingProvider { *; }
-keep class * implements org.tinylog.provider.LoggingProvider { *; }
